feature: add emojis to all message of the script

diff --git a/zvm b/zvm
--- a/zvm
+++ b/zvm
@@ -13,7 +13,7 @@ if [ ! -d "$ZVM_DIR" ]; then
 fi
 
 if ! echo "$PATH" | grep -q "$HOME/.zvm/current"; then
-	echo "Setting up initial PATH for .zvm/current..."
+	echo "🔧 Setting up initial PATH for .zvm/current..."
 
 	if [ -f "$HOME/.bashrc" ]; then
 		echo 'export PATH="$PATH:$HOME/.zvm/current"' >> "$HOME/.bashrc"
@@ -21,54 +21,54 @@ if ! echo "$PATH" | grep -q "$HOME/.zvm/current"; then
 
 	if [ -f "$HOME/.zshrc" ]; then
 		echo 'export PATH="$PATH:$HOME/.zvm/current"' >> "$HOME/.zshrc"
-   	fi
+				fi
 
-    if [ -d "$HOME/.config/fish" ]; then
-    	echo 'set -x PATH $PATH $HOME/.zvm/current' >> "$HOME/.config/fish/config.fish"
-    fi
+				if [ -d "$HOME/.config/fish" ]; then
+					echo 'set -x PATH $PATH $HOME/.zvm/current' >> "$HOME/.config/fish/config.fish"
+				fi
 
-    echo "Initial PATH setup complete."
+				echo "🔧 Initial PATH setup complete."
 fi
 
 # Ensure curl and jq are installed
 if ! command -v sha256sum &>/dev/null; then
-	echo "sha256sum could not be found. Please install it."
+	echo "❌ sha256sum could not be found. Please install it."
 	exit 1
 fi
 
 if ! command -v curl &>/dev/null; then
-	echo "curl could not be found. Please install it."
+	echo "❌ curl could not be found. Please install it."
 	exit 1
 fi
 
 if ! command -v jq &>/dev/null; then
-	echo "jq could not be found. Please install it."
+	echo "❌ jq could not be found. Please install it."
 	exit 1
 fi
 
 get_versions() {
 	# Fetch the JSON data from the Zig website
-	echo "Fetching Zig versions..."
+	echo "🔍 Fetching Zig versions..."
 	json_data=$(curl -s "$zig_download_json")
 }
 
 # Function to select a Zig version
 select_version() {
-	echo "Available versions:"
+	echo "📜 Available versions:"
 	versions=$(echo "$json_data" | jq -r 'keys[]' | sort -Vr)
 
 	if [ -z "$versions" ]; then
-		echo "No versions found or unable to fetch versions."
+		echo "❌ No versions found or unable to fetch versions."
 		exit 1
 	fi
 
 	select version in $versions; do
 		if [ -n "$version" ]; then
-			echo "Selected version: $version"
+			echo "✅ Selected version: $version"
 			selected_version="$version"
 			break
 		else
-			echo "Invalid selection. Please try again."
+			echo "❌ Invalid selection. Please try again."
 		fi
 	done
 }
@@ -79,11 +79,11 @@ download_asset() {
 	local architecture="$2"
 
 	if [ -z "$architecture" ]; then
-		echo "Available architectures for version $version:"
+		echo "📜 Available architectures for version $version:"
 		architectures=$(echo "$json_data" | jq -r --arg version "$version" '.[$version] | to_entries[] | select(.key | test("-")) | .key')
 
 		if [ -z "$architectures" ]; then
-			echo "No architectures found for the selected version."
+			echo "❌ No architectures found for the selected version."
 			exit 1
 		fi
 		select a in $architectures; do
@@ -95,21 +95,21 @@ download_asset() {
 	fi
 
 	if [ -n "$architecture" ]; then
-		echo "Selected architecture: $architecture"
+		echo "✅ Selected architecture: $architecture"
 		asset_url=$(echo "$json_data" | jq -r --arg version "$version" --arg architecture "$architecture" '.[$version][$architecture].tarball')
 		shasum=$(echo "$json_data" | jq -r --arg version "$version" --arg architecture "$architecture" '.[$version][$architecture].shasum')
-		echo "Downloading $architecture from $asset_url..."
+		echo "⬇️ Downloading $architecture from $asset_url..."
 		curl -L "$asset_url" -o $filename
-		echo "Download complete."
-		echo "Verifying signature for $filename..."
+		echo "✅ Download complete."
+		echo "🔍 Verifying signature for $filename..."
 		if [ "$(sha256sum zig.tar.gz | awk '{print $1}')" != "$shasum" ]; then
-			echo "Signature verification failed. Please try again."
+			echo "❌ Signature verification failed. Please try again."
 			rm $filename
 			exit 1
 		fi
-		echo "Signature verification successful."
+		echo "✅ Signature verification successful."
 	else
-		echo "Invalid selection. Please try again."
+		echo "❌ Invalid selection. Please try again."
 	fi
 }
 
@@ -124,9 +124,9 @@ list_versions() {
 	local versions=$(find "$ZVM_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
 
 	if [ -z "$versions" ]; then
-		echo "No versions installed."
+		echo "❌ No versions installed."
 	else
-		echo "Installed versions:"
+		echo "📜 Installed versions:"
 		for version in $versions; do
 			if [ "$version" == "$selected_version" ]; then
 				echo "* $version"
@@ -141,14 +141,14 @@ list_versions() {
 remove_version() {
 	local version="$1"
 	if [ -z "$version" ]; then
-		echo "Please provide a version to remove."
+		echo "❌ Please provide a version to remove."
 		return 1
 	fi
 	if [ -d "$ZVM_DIR/$version" ]; then
-		echo "Removing version $version..."
+		echo "🗑️ Removing version $version..."
 		rm -rf "$ZVM_DIR/$version"
 	else
-		echo "Version $version not found."
+		echo "❌ Version $version not found."
 		return 1
 	fi
 }
@@ -158,16 +158,16 @@ select_run() {
 	if [ -z "$1" ]; then
 		local versions=$(find "$ZVM_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
 		if [ -z "$versions" ]; then
-			echo "No versions installed."
+			echo "❌ No versions installed."
 			return 1
 		fi
 		select version in $versions; do
 			if [ -n "$version" ]; then
-				echo "Selected version: $version"
+				echo "✅ Selected version: $version"
 				export ZVM_VERSION="$version"
 				break
 			else
-				echo "Invalid selection. Please try again."
+				echo "❌ Invalid selection. Please try again."
 			fi
 		done
 	else
@@ -183,7 +183,7 @@ select_run() {
 
 	echo "export PATH=\"\$PATH:\$HOME/.zvm/current\"" >> "$HOME/.bashrc"
 
-	echo "zig version"
+	echo "🔧 zig version"
 	$HOME/.zvm/current/zig version
 }
 
@@ -201,7 +201,7 @@ get_system_architecture() {
 		FreeBSD-x86_64) echo "x86_64-freebsd" ;;
 		MINGW64_NT-*-x86_64) echo "x86_64-windows" ;;
 		MINGW32_NT-*-i686) echo "x86-windows" ;;
-		*) echo "Unsupported architecture"; exit 1 ;;
+		*) echo "❌ Unsupported architecture"; exit 1 ;;
 	esac
 }
 
@@ -218,22 +218,22 @@ install_version() {
 	fi
 
 	if [ -d "$ZVM_DIR/$version" ]; then
-		echo "Version $version already installed."
+		echo "❌ Version $version already installed."
 		return 1
 	fi
 
 	if [ -z "$architecture" ]; then
 		architecture=$(get_system_architecture)
-		echo "Detected system architecture: $architecture"
+		echo "🔍 Detected system architecture: $architecture"
 	fi
 
 	download_asset "$version" $architecture
 
 	mkdir -p "$ZVM_DIR/$version"
 
-	echo "Extracting $filename..."
+	echo "🔧 Extracting $filename..."
 	tar -xf $filename -C "$ZVM_DIR/$version" >/dev/null
-	echo "Extraction complete."
+	echo "✅ Extraction complete."
 
 	extractedfolder=$(ls $ZVM_DIR/$version/)
 	mv $ZVM_DIR/$version/${extractedfolder}/* $ZVM_DIR/$version/
@@ -241,7 +241,7 @@ install_version() {
 	rm $filename
 	rm -rf $extractedfolder
 
-	echo "Installed version $version."
+	echo "✅ Installed version $version."
 	select_run "$version"
 }
 
@@ -255,7 +255,7 @@ print_usage() {
 	echo "  remove      - Remove installed version"
 	echo "  install     - Install a new version"
 	echo "  use         - Select what version to run"
-	echo "  versions    - SHow all the versions avalable on zig website"
+	echo "  versions    - Show all the versions available on zig website"
 }
 
 zls_install() {
@@ -263,11 +263,11 @@ zls_install() {
 	local tag=$($ZVM_DIR/current/zig version)
 
 	if [ -f "$ZVM_DIR/$selected_version/zls" ]; then
-		echo "zls already installed."
+		echo "❌ zls already installed."
 		return 1
 	fi
 
-	echo "Installing zls..."
+	echo "🔧 Installing zls..."
 	cd $ZVM_DIR/$selected_version
 	git clone --branch $tag $zls_repo zls_src
 	cd zls_src
@@ -275,7 +275,7 @@ zls_install() {
 	mv zig-out/bin/zls $ZVM_DIR/$selected_version/zls
 	cd ../
 	rm -rf zls_src
-	echo "Installed zls."
+	echo "✅ Installed zls."
 }
 
 # switch for subcommands
